#!/bin/csh

# script to run the solver

# name of the file that contains the list of machines
set list_of_machines = `grep MACHINE_FILE DATA/Par_file | cut -c 27- `
set my_local_path = `grep LOCAL_PATH DATA/Par_file | cut -c 27- `

# read DATA/Par_file to get total number of nodes needed

set NPROC_XI = `grep NPROC_XI DATA/Par_file | cut -c 27- `
set NPROC_ETA = `grep NPROC_ETA DATA/Par_file | cut -c 27- `

# total number of nodes is product of values read
@ numnodes = $NPROC_XI * $NPROC_ETA

rm -f sources error*txt starttimeloop* timestamp* PI* RECORDHEADERS

if ( -f $list_of_machines ) then
  echo " "
  echo using machine file \"$list_of_machines\"
  echo " "
  echo list of active machines:
  echo " "
  cat $list_of_machines
  echo " "
endif

echo NPROC_XI = $NPROC_XI
echo NPROC_ETA = $NPROC_ETA
echo " "
echo starting MPI solver on $numnodes nodes
echo " "
echo starting run in current directory $PWD
echo " "
echo mesh files will be read from directory $my_local_path
echo " "

set MPIRUN="/home/local/mpich/bin/mpirun"

#### use this on Beowulf
# mpirun -nolocal -machinefile $list_of_machines -np $numnodes $PWD/xspecfem3D 
 $MPIRUN -nolocal -machinefile $list_of_machines -np $numnodes $PWD/xspecfem3D 

#### use this on SGI
# mpirun -np $numnodes xspecfem3D

#### use this on Compaq Dec Alpha
# dmpirun -np $numnodes xspecfem3D

